### ISSUE TITLE
SQLAlchemy Error running Web and Postgres in different pods

### ISSUE THREAD

**Issue by chasain** [trotto/go-links#51]
Thanks for making this project, it's awesome.

We're running this service in k8s on GKE using a postgres:12 image as the database container in a seperate pod. We're seeing a lot of issues in the logs like below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/go-links/server/src/main.py", line 77, in home
    if not current_user.is_authenticated:
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/usr/local/lib/python3.7/site-packages/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/usr/src/app/go-links/server/src/main.py", line 54, in load_user
    return get_user_by_id(user_id)
  File "/usr/src/app/go-links/server/src/modules/users/helpers.py", line 34, in get_user_by_id
    return models.User.get_by_id(user_id)
  File "/usr/src/app/go-links/server/src/modules/data/implementations/postgres/users.py", line 27, in get_by_id
    return User.query.get(int(id))
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT "user".id AS user_id, "user".created AS user_created, "user".modified AS user_modified, "user".email AS user_email, "user".organization AS user_organization, "user".role AS user_role, "user".accepted_terms_at AS user_accepted_terms_at, "user".domain_type AS user_domain_type, "user".notifications AS user_notifications 
FROM "user" 
WHERE "user".id = %(param_1)s]
[parameters: {'param_1': 2}]
```

I'm testing the workaround listed here now: https://stackoverflow.com/questions/55457069/how-to-fix-operationalerror-psycopg2-operationalerror-server-closed-the-conn

It's been up and running for a few hours with no issues so far so looking good. Here's my patch on server/src/main.py

```
if get_database() == 'postgres':
    app.config['SQLALCHEMY_DATABASE_URI'] = get_config()['postgres']['url']
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    global db
    global migrate
    class SQLAlchemy(_BaseSQLAlchemy):
      def apply_pool_defaults(self, app, options):
          super(SQLAlchemy, self).apply_pool_defaults(app, options)
          options["pool_pre_ping"] = True
    db = SQLAlchemy(app)
    migrate = Migrate(app, db)
```

**Comment by itsojon** [comment]
@chasain you're so welcome, and thank you for creating this issue! This makes sense, and the patch looks good. Feel free to send a PR, or I can add it in the near future. And of course let me know if you see the issue again even with the patch.

Also, we love learning how self-hosting teams are using Trotto, so if you're willing to have a quick chat about the tool, send me an email at jon@trot.to, or use the live chat at https://www.trot.to.
